name: layra3
description: "Layra Voice Assistant"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  lottie: ^3.1.0
  speech_to_text: ^7.0.0
  flutter_tts: ^4.2.3
  permission_handler: ^12.0.0+1
  path_provider: ^2.1.2
  record: ^5.0.4
  io: ^1.0.5
  convert: ^3.1.2
  flutter_tts: ^3.8.5 # Veya en son sürümü kontrol edin
  flutter_dotenv: ^5.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/bg.png
    - assets/lyra.png
    - assets/lyrabg.png
    - assets/komutlar.json

    - assets/animations/
